"""Add profile fields to User model

Revision ID: 113ae9fb16d4
Revises: b46df1103731
Create Date: 2026-03-18 12:02:39.205907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '113ae9fb16d4'
down_revision = 'b46df1103731'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('mobile_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('age', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('gender', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('gender')
        batch_op.drop_column('age')
        batch_op.drop_column('mobile_number')
        batch_op.drop_column('full_name')

    # ### end Alembic commands ###
