"""Add DisasterModule table

Revision ID: 3017577e3f1d
Revises: 532fa22a9682
Create Date: 2025-09-17 23:35:52.360114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3017577e3f1d'
down_revision = '532fa22a9682'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disaster_module',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('disaster_module', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_disaster_module_category'), ['category'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('disaster_module', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_disaster_module_category'))

    op.drop_table('disaster_module')
    # ### end Alembic commands ###
