"""Add RescueService table

Revision ID: a835e7f2ba6f
Revises: efa171bd2dc6
Create Date: 2025-09-18 00:14:08.742309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a835e7f2ba6f'
down_revision = 'efa171bd2dc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rescue_service',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_name', sa.String(length=150), nullable=False),
    sa.Column('service_type', sa.String(length=50), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('contact_number', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rescue_service', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rescue_service_service_type'), ['service_type'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rescue_service', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rescue_service_service_type'))

    op.drop_table('rescue_service')
    # ### end Alembic commands ###
