"""Reset database to core features

Revision ID: b46df1103731
Revises: 
Create Date: 2025-09-19 02:58:11.519010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b46df1103731'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alert', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alert_region'), ['region'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_timestamp'), ['timestamp'], unique=False)

    op.create_table('disaster_module',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('disaster_module', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_disaster_module_category'), ['category'], unique=False)

    op.create_table('rescue_service',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_name', sa.String(length=150), nullable=False),
    sa.Column('service_type', sa.String(length=50), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('contact_number', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rescue_service', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rescue_service_service_type'), ['service_type'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    with op.batch_alter_table('rescue_service', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rescue_service_service_type'))

    op.drop_table('rescue_service')
    with op.batch_alter_table('disaster_module', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_disaster_module_category'))

    op.drop_table('disaster_module')
    with op.batch_alter_table('alert', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alert_timestamp'))
        batch_op.drop_index(batch_op.f('ix_alert_severity'))
        batch_op.drop_index(batch_op.f('ix_alert_region'))

    op.drop_table('alert')
    # ### end Alembic commands ###
