"""Add Alert table

Revision ID: efa171bd2dc6
Revises: 3017577e3f1d
Create Date: 2025-09-17 23:43:06.277161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efa171bd2dc6'
down_revision = '3017577e3f1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alert', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alert_region'), ['region'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alert', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alert_timestamp'))
        batch_op.drop_index(batch_op.f('ix_alert_severity'))
        batch_op.drop_index(batch_op.f('ix_alert_region'))

    op.drop_table('alert')
    # ### end Alembic commands ###
